name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Retrieve the cached "node_modules" directory (if present)
      uses: actions/cache@v2
      id: node-cache
      with:
       path: node_modules
       key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    
    - name: Install dependencies (if the cached directory was not found)
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm ci
    
    - uses: JS-DevTools/npm-publish@v1
      id: npm-publish
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public

    - if: steps.npm-publish.outputs.type != 'none'
      name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true